dist: trusty
sudo: required
language: python
python:
    - "3.4_with_system_site_packages"
branches:
    - master
before_install:
    - "sudo apt-get -y update"
    - "sudo apt-get install -y python3-pip python3-gi python3-gobject gir1.2-gtk-3.0"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "sleep 3;"
install:
    - "sudo pip3 install cairosvg pylint codacy-coverage coverage"
script:
    - "find -name \"*.py\" | xargs pylint --rcfile=.pylintrc $1"
after_success:
    - "sudo -E coverage run hardcode-tray.py --apply --theme hicolor"
    - "coverage xml"
    - "python-codacy-coverage -r coverage.xml"
