language: python
sudo: required
python:
  - 3.3
before_install:
  - sudo apt-get update
  - curl http://python-distribute.org/distribute_setup.py | sudo python3
  - curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3
install:
  - sudo apt-get -y install python3-gi inkscape
  - pip install coveralls
  - sudo pip-3.3 install coverage
script:
  sudo -E coverage run script.py --apply 
after_success:
  coveralls
