language: python
sudo: true
python: 
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gir1.2-gtk-3.0 
install:
    - pip install cairosvg
script:
    - sudo -E python3 script.py
