language: python
sudo: required
dist: trusty
python:
  - 3.3
before_install:
  - sudo apt-get update
install:
  - sudo apt-get -y install python3-gi inkscape python3-pip gir1.2-gtk-3.0 gtk+3.0
  - sudo pip3 install coveralls
  - sudo pip3 install coverage
script:
  sudo -E coverage run script.py --apply 
after_success:
  coveralls
