language: python
sudo: required
python:
  - 3.3
install:
  - sudo apt-get install python3-gi inkscape
  - pip install coveralls coverage
script:
  sudo -E coverage run script.py --apply 
after_success:
  coveralls
